<a href="https://colab.research.google.com/github/SPYACO-04/Machine-Learning/blob/main/NumpyEx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Basic Array Creation

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
a = ([1,2,3.4,5,"hello"])
a

[1, 2, 3.4, 5, 'hello']

In [ ]:
a = np.array([1,23,43,3.4])
a

array([ 1. , 23. , 43. ,  3.4])

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
np.array(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Function


In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.zeros((4,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones((6,7))
arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

Random Generation Function

In [ ]:
np.random.rand(10)

array([0.08811055, 0.54858949, 0.43659964, 0.93071343, 0.1679747 ,
       0.22606286, 0.53991518, 0.77717703, 0.63190266, 0.65864693])

In [ ]:
np.random.randint(10,20,10)

array([18, 12, 16, 17, 11, 15, 14, 12, 15, 11])

Array Attributes

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

Array Method

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

Reshaping Array

In [ ]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

**Numpy Indexing and slicing of vectors**

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr_slice = arr[1::5]
arr_slice

array([12, 17])

In [ ]:
arr[5]

np.int64(16)

**Numpy Indexing and slicing of Matrix**

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[5]

array([26, 27, 28, 29, 30])

In [ ]:
arr[3:6,3:5]


array([[19, 20],
       [24, 25],
       [29, 30]])

**Boolean Indexing**

In [ ]:
rr = np.arange(11,21)
rr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bix = rr % 2 == 0
bix

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr = rr[bix]
arr

array([12, 14, 16, 18, 20])

**Array Operations**

In [ ]:
import numpy as np

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9])

In [ ]:
a1 + a2

ValueError: operands could not be broadcast together with shapes (5,) (4,) 